/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Insercion;

/**
 *
 * @author MS
 */
public class vistaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form vistaAdministrador
     */
    public vistaAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jTextField13 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jTextField15 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(580, 621));
        setSize(new java.awt.Dimension(580, 621));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Administrador");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 150, 30);

        jLabel2.setText("Autobus");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 60, 50, 16);

        jTextField1.setToolTipText("");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(230, 110, 90, 22);

        jTextField3.setToolTipText("");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(120, 110, 90, 22);

        jTextField4.setToolTipText("");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(340, 110, 90, 22);

        jLabel3.setText("Marca");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 90, 35, 16);

        jLabel4.setText("Modelo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(360, 90, 41, 20);

        jLabel5.setText("Asientos");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 90, 50, 16);

        jLabel6.setText("Chofer");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 200, 38, 16);

        jTextField5.setToolTipText("");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(30, 250, 90, 22);

        jLabel7.setText("Numero de Empleado");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 230, 130, 16);

        jButton1.setText("Eliminar");
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 150, 79, 25);

        jButton3.setText("Limpiar");
        getContentPane().add(jButton3);
        jButton3.setBounds(300, 150, 75, 25);

        jButton2.setText("Agregar");
        getContentPane().add(jButton2);
        jButton2.setBounds(80, 150, 79, 25);

        jLabel8.setText("Nombre");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(160, 230, 50, 16);

        jTextField6.setToolTipText("");
        getContentPane().add(jTextField6);
        jTextField6.setBounds(140, 250, 90, 22);

        jTextField7.setToolTipText("");
        getContentPane().add(jTextField7);
        jTextField7.setBounds(350, 250, 60, 22);

        jLabel9.setText("Nacimiento");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(260, 230, 70, 16);

        jButton4.setText("Agregar");
        getContentPane().add(jButton4);
        jButton4.setBounds(80, 280, 79, 25);

        jButton5.setText("Eliminar");
        getContentPane().add(jButton5);
        jButton5.setBounds(190, 280, 79, 25);

        jButton6.setText("Limpiar");
        getContentPane().add(jButton6);
        jButton6.setBounds(300, 280, 75, 25);

        jTextField8.setToolTipText("");
        getContentPane().add(jTextField8);
        jTextField8.setBounds(250, 250, 40, 22);

        jTextField9.setToolTipText("");
        getContentPane().add(jTextField9);
        jTextField9.setBounds(300, 250, 40, 22);

        jLabel10.setText("Ruta");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 320, 30, 16);

        jLabel11.setText("Origen");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(150, 350, 40, 16);

        jTextField10.setToolTipText("");
        getContentPane().add(jTextField10);
        jTextField10.setBounds(130, 370, 90, 22);

        jButton7.setText("Agregar");
        getContentPane().add(jButton7);
        jButton7.setBounds(90, 410, 79, 25);

        jButton8.setText("Eliminar");
        getContentPane().add(jButton8);
        jButton8.setBounds(200, 410, 79, 25);

        jTextField2.setToolTipText("");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(240, 370, 90, 22);

        jLabel12.setText("Destino");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(250, 350, 42, 16);

        jLabel13.setText("Intermedios");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(360, 350, 70, 20);

        jTextField11.setToolTipText("");
        getContentPane().add(jTextField11);
        jTextField11.setBounds(350, 370, 90, 22);

        jButton9.setText("Limpiar");
        getContentPane().add(jButton9);
        jButton9.setBounds(310, 410, 75, 25);

        jButton10.setText("Cerrar Sesión");
        getContentPane().add(jButton10);
        jButton10.setBounds(267, 20, 130, 25);

        jLabel14.setText("Viaje");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 450, 30, 16);

        jLabel15.setText("ID Ruta");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(30, 480, 50, 16);

        jTextField12.setToolTipText("");
        getContentPane().add(jTextField12);
        jTextField12.setBounds(20, 500, 90, 22);

        jButton11.setText("Agregar");
        getContentPane().add(jButton11);
        jButton11.setBounds(90, 540, 79, 25);

        jButton12.setText("Eliminar");
        getContentPane().add(jButton12);
        jButton12.setBounds(200, 540, 79, 25);

        jTextField13.setToolTipText("");
        getContentPane().add(jTextField13);
        jTextField13.setBounds(130, 500, 90, 22);

        jLabel16.setText("Fecha");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(160, 480, 34, 16);

        jLabel17.setText("Hora Salida");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(250, 480, 70, 20);

        jTextField14.setToolTipText("");
        getContentPane().add(jTextField14);
        jTextField14.setBounds(400, 500, 40, 22);

        jButton13.setText("Limpiar");
        getContentPane().add(jButton13);
        jButton13.setBounds(310, 540, 75, 25);

        jTextField15.setToolTipText("");
        getContentPane().add(jTextField15);
        jTextField15.setBounds(20, 370, 90, 22);

        jLabel18.setText("ID Ruta");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(30, 350, 50, 16);

        jLabel19.setText("Duracion");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(360, 480, 50, 20);

        jTextField17.setToolTipText("");
        getContentPane().add(jTextField17);
        jTextField17.setBounds(240, 500, 40, 22);

        jTextField16.setToolTipText("");
        getContentPane().add(jTextField16);
        jTextField16.setBounds(290, 500, 40, 22);

        jTextField18.setToolTipText("");
        getContentPane().add(jTextField18);
        jTextField18.setBounds(350, 500, 40, 22);

        jTextField19.setToolTipText("");
        getContentPane().add(jTextField19);
        jTextField19.setBounds(20, 110, 90, 22);

        jLabel20.setText("ID Bus");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(45, 90, 40, 16);

        jTextField20.setToolTipText("");
        getContentPane().add(jTextField20);
        jTextField20.setBounds(460, 500, 90, 22);

        jLabel21.setText("Precio");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(490, 480, 40, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
