/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Insercion;

/**
 *
 * @author MS
 */
public class vistaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form vistaAdministrador
     */
    public vistaAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AsientosTextField = new javax.swing.JTextField();
        MarcaTextField = new javax.swing.JTextField();
        ModeloTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NumEmpleadoTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        EliminarBusButton = new javax.swing.JButton();
        LimpiarBusButton = new javax.swing.JButton();
        AgregarBusButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        NombreTextField = new javax.swing.JTextField();
        anioNacimientoTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        AgregarChoferButton = new javax.swing.JButton();
        EliminarChoferButton = new javax.swing.JButton();
        LimpiarChoferButton = new javax.swing.JButton();
        DiaNacimientoTextField = new javax.swing.JTextField();
        mesNacimientoTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        origenTextField = new javax.swing.JTextField();
        AgregarRutaButton = new javax.swing.JButton();
        EliminarRutaButton = new javax.swing.JButton();
        destinoTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        intermediosTextField = new javax.swing.JTextField();
        LimpiarRutaButton = new javax.swing.JButton();
        CerrarSesionButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        idRutaTextFieldViaje = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        minutosDuraTextField = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        idRutaTextFieldRuta = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        horaTextField = new javax.swing.JTextField();
        minutoTextField = new javax.swing.JTextField();
        horaDuraTextField = new javax.swing.JTextField();
        IDBusTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        precioTextField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        DiaNacimientoTextField1 = new javax.swing.JTextField();
        mesNacimientoTextField1 = new javax.swing.JTextField();
        anioNacimientoTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 640));
        setMinimumSize(new java.awt.Dimension(600, 640));
        setPreferredSize(new java.awt.Dimension(600, 640));
        setSize(new java.awt.Dimension(600, 640));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Administrador");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 150, 30);

        jLabel2.setText("Autobus");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 60, 50, 16);

        AsientosTextField.setToolTipText("");
        getContentPane().add(AsientosTextField);
        AsientosTextField.setBounds(230, 110, 90, 22);

        MarcaTextField.setToolTipText("");
        getContentPane().add(MarcaTextField);
        MarcaTextField.setBounds(120, 110, 90, 22);

        ModeloTextField.setToolTipText("");
        getContentPane().add(ModeloTextField);
        ModeloTextField.setBounds(340, 110, 90, 22);

        jLabel3.setText("Marca");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 90, 35, 16);

        jLabel4.setText("Modelo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(360, 90, 41, 20);

        jLabel5.setText("Asientos");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 90, 50, 16);

        jLabel6.setText("Chofer");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 200, 38, 16);

        NumEmpleadoTextField.setToolTipText("");
        getContentPane().add(NumEmpleadoTextField);
        NumEmpleadoTextField.setBounds(30, 250, 90, 22);

        jLabel7.setText("Numero de Empleado");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 230, 130, 16);

        EliminarBusButton.setText("Eliminar");
        getContentPane().add(EliminarBusButton);
        EliminarBusButton.setBounds(190, 150, 79, 25);

        LimpiarBusButton.setText("Limpiar");
        getContentPane().add(LimpiarBusButton);
        LimpiarBusButton.setBounds(300, 150, 75, 25);

        AgregarBusButton.setText("Agregar");
        getContentPane().add(AgregarBusButton);
        AgregarBusButton.setBounds(80, 150, 79, 25);

        jLabel8.setText("Nombre");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(160, 230, 50, 16);

        NombreTextField.setToolTipText("");
        getContentPane().add(NombreTextField);
        NombreTextField.setBounds(140, 250, 90, 22);

        anioNacimientoTextField.setToolTipText("");
        getContentPane().add(anioNacimientoTextField);
        anioNacimientoTextField.setBounds(330, 250, 60, 22);

        jLabel9.setText("Nacimiento");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(260, 230, 70, 16);

        AgregarChoferButton.setText("Agregar");
        getContentPane().add(AgregarChoferButton);
        AgregarChoferButton.setBounds(80, 280, 79, 25);

        EliminarChoferButton.setText("Eliminar");
        getContentPane().add(EliminarChoferButton);
        EliminarChoferButton.setBounds(190, 280, 79, 25);

        LimpiarChoferButton.setText("Limpiar");
        getContentPane().add(LimpiarChoferButton);
        LimpiarChoferButton.setBounds(310, 280, 75, 25);

        DiaNacimientoTextField.setToolTipText("");
        getContentPane().add(DiaNacimientoTextField);
        DiaNacimientoTextField.setBounds(250, 250, 40, 22);

        mesNacimientoTextField.setToolTipText("");
        getContentPane().add(mesNacimientoTextField);
        mesNacimientoTextField.setBounds(290, 250, 40, 22);

        jLabel10.setText("Ruta");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 320, 30, 16);

        jLabel11.setText("Origen");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(150, 350, 40, 16);

        origenTextField.setToolTipText("");
        getContentPane().add(origenTextField);
        origenTextField.setBounds(130, 370, 90, 22);

        AgregarRutaButton.setText("Agregar");
        getContentPane().add(AgregarRutaButton);
        AgregarRutaButton.setBounds(90, 410, 79, 25);

        EliminarRutaButton.setText("Eliminar");
        getContentPane().add(EliminarRutaButton);
        EliminarRutaButton.setBounds(200, 410, 79, 25);

        destinoTextField.setToolTipText("");
        getContentPane().add(destinoTextField);
        destinoTextField.setBounds(240, 370, 90, 22);

        jLabel12.setText("Destino");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(250, 350, 42, 16);

        jLabel13.setText("Intermedios");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(360, 350, 70, 20);

        intermediosTextField.setToolTipText("");
        getContentPane().add(intermediosTextField);
        intermediosTextField.setBounds(350, 370, 90, 22);

        LimpiarRutaButton.setText("Limpiar");
        getContentPane().add(LimpiarRutaButton);
        LimpiarRutaButton.setBounds(310, 410, 75, 25);

        CerrarSesionButton.setText("Cerrar Sesión");
        getContentPane().add(CerrarSesionButton);
        CerrarSesionButton.setBounds(430, 20, 130, 25);

        jLabel14.setText("Viaje");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 450, 30, 16);

        jLabel15.setText("ID Ruta");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(30, 480, 50, 16);

        idRutaTextFieldViaje.setToolTipText("");
        getContentPane().add(idRutaTextFieldViaje);
        idRutaTextFieldViaje.setBounds(20, 500, 90, 22);

        jButton11.setText("Agregar");
        getContentPane().add(jButton11);
        jButton11.setBounds(90, 540, 79, 25);

        jButton12.setText("Eliminar");
        getContentPane().add(jButton12);
        jButton12.setBounds(200, 540, 79, 25);

        jLabel16.setText("Fecha");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(160, 480, 34, 16);

        jLabel17.setText("Hora Salida");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(290, 480, 70, 20);

        minutosDuraTextField.setToolTipText("");
        getContentPane().add(minutosDuraTextField);
        minutosDuraTextField.setBounds(420, 500, 40, 22);

        jButton13.setText("Limpiar");
        getContentPane().add(jButton13);
        jButton13.setBounds(310, 540, 75, 25);

        idRutaTextFieldRuta.setToolTipText("");
        getContentPane().add(idRutaTextFieldRuta);
        idRutaTextFieldRuta.setBounds(20, 370, 90, 22);

        jLabel18.setText("ID Ruta");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(30, 350, 50, 16);

        jLabel19.setText("Duracion");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(390, 480, 50, 20);

        horaTextField.setToolTipText("");
        getContentPane().add(horaTextField);
        horaTextField.setBounds(280, 500, 40, 22);

        minutoTextField.setToolTipText("");
        getContentPane().add(minutoTextField);
        minutoTextField.setBounds(320, 500, 40, 22);

        horaDuraTextField.setToolTipText("");
        getContentPane().add(horaDuraTextField);
        horaDuraTextField.setBounds(380, 500, 40, 22);

        IDBusTextField.setToolTipText("");
        getContentPane().add(IDBusTextField);
        IDBusTextField.setBounds(20, 110, 90, 22);

        jLabel20.setText("ID Bus");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(45, 90, 40, 16);

        precioTextField.setToolTipText("");
        getContentPane().add(precioTextField);
        precioTextField.setBounds(480, 500, 90, 22);

        jLabel21.setText("Precio");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(510, 480, 40, 16);

        DiaNacimientoTextField1.setToolTipText("");
        getContentPane().add(DiaNacimientoTextField1);
        DiaNacimientoTextField1.setBounds(120, 500, 40, 22);

        mesNacimientoTextField1.setToolTipText("");
        getContentPane().add(mesNacimientoTextField1);
        mesNacimientoTextField1.setBounds(160, 500, 40, 22);

        anioNacimientoTextField1.setToolTipText("");
        getContentPane().add(anioNacimientoTextField1);
        anioNacimientoTextField1.setBounds(200, 500, 60, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AgregarBusButton;
    public javax.swing.JButton AgregarChoferButton;
    public javax.swing.JButton AgregarRutaButton;
    public javax.swing.JTextField AsientosTextField;
    private javax.swing.JButton CerrarSesionButton;
    public javax.swing.JTextField DiaNacimientoTextField;
    public javax.swing.JTextField DiaNacimientoTextField1;
    public javax.swing.JButton EliminarBusButton;
    public javax.swing.JButton EliminarChoferButton;
    public javax.swing.JButton EliminarRutaButton;
    public javax.swing.JTextField IDBusTextField;
    public javax.swing.JButton LimpiarBusButton;
    public javax.swing.JButton LimpiarChoferButton;
    public javax.swing.JButton LimpiarRutaButton;
    public javax.swing.JTextField MarcaTextField;
    public javax.swing.JTextField ModeloTextField;
    public javax.swing.JTextField NombreTextField;
    public javax.swing.JTextField NumEmpleadoTextField;
    public javax.swing.JTextField anioNacimientoTextField;
    public javax.swing.JTextField anioNacimientoTextField1;
    public javax.swing.JTextField destinoTextField;
    public javax.swing.JTextField horaDuraTextField;
    public javax.swing.JTextField horaTextField;
    public javax.swing.JTextField idRutaTextFieldRuta;
    public javax.swing.JTextField idRutaTextFieldViaje;
    public javax.swing.JTextField intermediosTextField;
    public javax.swing.JButton jButton11;
    public javax.swing.JButton jButton12;
    public javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField mesNacimientoTextField;
    public javax.swing.JTextField mesNacimientoTextField1;
    public javax.swing.JTextField minutoTextField;
    public javax.swing.JTextField minutosDuraTextField;
    public javax.swing.JTextField origenTextField;
    public javax.swing.JTextField precioTextField;
    // End of variables declaration//GEN-END:variables
}
